name: Trigger AWX Job

on:
  push:
    branches:
      - master  # Replace with your branch name

jobs:
  trigger-awx-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger AWX Job
        env:
          AWX_SERVER: 'http://192.168.10.4'  # Replace with your AWX server URL
          AWX_USERNAME: 'admin'      # Replace with your AWX username
          AWX_PASSWORD: 'Hello@2010'      # Replace with your AWX password or token
          AWX_TEMPLATE_ID: '9'    # Replace with the ID of your AWX job template
        run: |
          curl -X POST -H "Content-Type: application/json" -u "$AWX_USERNAME:$AWX_PASSWORD" \
               "$AWX_SERVER/api/v2/job_templates/$AWX_TEMPLATE_ID/launch/" \
               -d '{"limit": "your-limit"}'
